name: 'Composite action'
description: 'Composite action with nested composite action'
runs:
  using: 'composite'
  steps:
    - uses: Andrew-Test-Org/Public-Test-Repo/.github/actions/composite/myNestedCompositeAction@Rory-NestedCompoundAction
