name: Set up Node
description: Set up Node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
        cache: npm

    - shell: bash
      run: |
        if [ -z ${CI+x} ]; then
          echo 'not CI';
        else
          echo 'CI';
        fi

    - shell: bash
      run: sleep 60

    - id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install node packages
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: npm ci
