name: 'Javascript action'
description: 'Run a custom Javascript Action'
inputs:
    GITHUB_TOKEN:
        description: Auth token for Expensify.cash Github
        required: true
runs:
    using: 'node12'
    main: './index.js'
