on: workflow_dispatch
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.RORY_TEST_ACCOUNT_TOKEN }}

      - run: |
          git config user.name roryabrahamtest
          git config user.email roryabrahamtest@gmail.com

      - run: npm version patch

      - run: git push origin main

      - run: |
          git fetch origin staging
          git branch -D staging
          git checkout -b staging
          git push --force origin staging
