name: 'Caller workflow'
on:
  push:
    branches: [Rory-TestCallableWorkflow]
jobs:
  main:
    uses: ./.github/workflows/callableWorkflow.yml

  alertSuccess:
    needs: main
    runs-on: ubuntu-latest
    if: ${{ always() && needs.main.result == 'success' }}
    steps:
      - run: echo 'Success!'

  alertFailure:
    needs: main
    runs-on: ubuntu-latest
    if: ${{ always() && needs.main.result == 'failure' }}
    steps:
      - run: echo 'Failure!'
