name: Callable Workflow

on:
  workflow_call:
    secrets:
      RENAMED_SECRET:
jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      CONDITION: ${{ steps.check.outputs.CONDITION }}
    steps:
      - id: check
        run: echo "::set-output name=CONDITION::true"

  main:
    runs-on: ubuntu-latest
    needs: pre
    if: ${{ fromJSON(needs.pre.outputs.CONDITION) }}
    steps:
      - run: echo 'Callable workflow executed'

      - run: gh pr comment https://github.com/Andrew-Test-Org/Public-Test-Repo/pull/306 --body "Test comment"
        env:
          GH_TOKEN: ${{ secrets.RENAMED_SECRET }}
