name: Callable Workflow

on:
  workflow_call:
    secrets:
      RORY_TOKEN:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Callable workflow executed'

      - run: gh pr comment 306 --body "Test comment"
        env:
          GH_TOKEN: ${{ secrets.RORY_TOKEN }}
