name: 'Caller workflow'
on:
  push:
    branches: [Rory-TestCallableWorkflow]
jobs:
  main:
    uses: ./.github/workflows/callableWorkflow.yml

  dependent:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Alert failure
        if: ${{ failure() }}
        run: echo 'Failure!'
