name: Test Concurrent Workflow
on:
  push:
    branches: [Rory-TestConcurrency]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  concurrent:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Starting workflow'
      - run: sleep 60
      - run: echo 'Ending workflow'
