name: Dispatchable Workflow
on:
  workflow_call:
  workflow_dispatch:
jobs:
  triggerCallableWorkflow:
    uses: Andrew-Test-Org/Public-Test-Repo/.github/workflows/callableWorkflow.yml@main
    secrets:
      RORY_TOKEN: ${{ secrets.RORY_TOKEN }}
