name: 'Workflow that executes on the Issues:Labeled event'

on:
  issues:
     types: labeled

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print labeled event.
        run: echo ${{ toJson(github.event) }}

      - run: echo "Dummy commit 3"
