name: 'Workflow that executes on the Issues:Labeled event'

on:
  issues:
     types: labeled

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        run: sudo apt-get install python3-setuptools

      - name: Print labeled event.
        run: python3 ./printJSON.py3 ${{ github.event }}
