name: PullRequestTarget

on:
  pull_request_target:
      types: [opened, closed, synchronize]
      branches-ignore: [staging, production]

jobs:
    pullRequestTarget:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Testing auto-approve with a forked repo'

            - name: Check for an auto approve
              # Version: 2.0.0
              uses: roryabraham/auto-approve-action@1d9eaca19e005b39bc4495c51fc7439734b2753d
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
