# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echoActor:
    runs-on: macos-latest
    steps:
      - name: Echo actor
        run: echo ${{ github.actor }}

  # This workflow contains a single job called "build"
  build:
    if: github.actor == 'AndrewGable'
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ toJSON(github.event) }} && echo "I am Andrew" && exit 0
