name: PR Workflow

on:
  pull_request:
    branches-ignore: [main, 'ignore-*']

jobs:
  chooseActions:
    runs-on: ubuntu-latest
    outputs:
      isTrue: 'true'
      isFalse: 'false'
    steps:
      - run: echo "Hello world!"

  shouldRun:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: ${{ needs.chooseActions.outputs.isTrue == 'true' }}
    steps:
      - run: echo "Hello world!"

  shouldNotRun:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: ${{ needs.chooseActions.outputs.isFalse == 'true' }}
    steps:
      - run: echo "Hello world!"

  shouldRunWithOR:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: |
      needs.chooseActions.outputs.isTrue == 'true' ||
      needs.chooseActions.outputs.isFalse == 'false'
    steps:
      - run: echo "Hello world!"

  shouldRunWithAND:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: |
      needs.chooseActions.outputs.isTrue == 'true' &&
      needs.chooseActions.outputs.isFalse == 'false'
    steps:
      - run: echo "Hello world!"

  shouldNotRunWithAND:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: |
      needs.chooseActions.outputs.isTrue == 'true' &&
      needs.chooseActions.outputs.isFalse == 'true'
    steps:
      - run: echo "Hello world!"
