name: Push Workflow

# Controls when the action will run.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"
      
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Generate branch name
        run: echo "BRANCH_NAME=botify-bump-version-$(uuidgen)" >> $GITHUB_ENV

      - name: Create branch for version-bump pull request
        run: git checkout -b $BRANCH_NAME

