name: Push Workflow

# Controls when the action will run.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echoActor:
    runs-on: macos-latest
    outputs:
      isActorRory: ${{ steps.isActorRory.outputs.IS_ACTOR_RORY }}
    steps:
      - name: Echo actor
        run: echo ${{ github.actor }}

      - name: Is Actor Rory?
        id: isActorRory
        run: echo "::set-output name=IS_ACTOR_RORY::${{ github.actor == 'roryabraham' && 'blah' == 'blah' }}"

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    needs: echoActor
    if: ${{
      needs.echoActor.outputs.isActorRory == 'true' &&
      'blah' == 'blah'
    }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a nested script
        run: echo "Hello $(echo 'World')!"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ toJSON(github.event) }} && echo "I am Andrew" && exit 0

  echoEnvironment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .github/actions/echoEnvironment@0fa33a3c6e3a74834829db7e78b6a213f8d7a2d1
    env:
      MY_BOOL: true

  envTest:
    runs-on: ubuntu-latest
    env:
      SHOULD_DEPLOY_PRODUCTION: ${{ false }}
    steps:
      - name: Run if true
        if: env.SHOULD_DEPLOY_PRODUCTION
        run: echo "I am running if I am true, I am:" ${{ env.SHOULD_DEPLOY_PRODUCTION }}
