name: Push Workflow

# Controls when the action will run.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chooseActions:
    runs-on: ubuntu-latest
    outputs:
      isTrue: ${{ true }}
      isFalse: ${{ false }}
    steps:
      - run: echo "Hello world!"

  shouldRun:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: ${{ needs.chooseActions.outputs.isTrue == 'true' }}

  shouldNotRun:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: ${{ needs.chooseActions.outputs.isFalse == 'false' }}
  
  shouldRunWithOR:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: |
      ${{ needs.chooseActions.outputs.isTrue == 'true' }} ||
      ${{ needs.chooseActions.outputs.isFalse == 'false' }}

  shouldRunWithAND:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: |
      ${{ needs.chooseActions.outputs.isTrue == 'true' }} &&
      ${{ needs.chooseActions.outputs.isFalse == 'false' }}

  shouldNotRunWithAND:
    runs-on: ubuntu-latest
    needs: chooseActions
    if: |
      ${{ needs.chooseActions.outputs.isTrue == 'true' }} &&
      ${{ needs.chooseActions.outputs.isFalse == 'true' }}