name: Push Workflow

# Controls when the action will run.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  myJobToWaitFor:
    runs-on: ubuntu-latest
    outputs:
      isTrue: 'true'
      isFalse: 'false'
    steps:
      - run: echo "Hello world!"
