name: Push Workflow

# Controls when the action will run.
on:
  push:

env:
  MY_ENV: 'foo'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  myJobToWaitFor:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.MY_ENV }}

      - run: echo ${{ env.MY_ENV }}
        env:
          MY_ENV: 'bar'

      - run: echo ${{ env.MY_ENV }}