name: 'Release created workflow'

on:
  release:
    -types: published

jobs:
  release-created-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set iOS version in ENV
        run: |
          echo "IOS_VERSION=$(echo '${{ github.event.release.tag_name }}' | tr '-' '.')" >> $GITHUB_ENV
          echo "iOS version is: ${{ env.IOS_VERSION }}"

      - name: Print ios version
        run: echo ${{ env.IOS_VERSION }}

      - name: Print release event
        run: echo "${{ toJSON(github.event) }}"
