name: 'Release created workflow'

on:
  release:
    -types: published

jobs:
  release-created-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print ios version
        run: echo "github.event.tag_name" | tr '-' '.'

      - name: Print release event.
        run: echo "${{ toJson(github.event) }}"
