name: Test Workflow Dispatch

on: workflow_dispatch

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Auto-approve the PR
        run: gh pr review 310 --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
