name: sleep
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Output inputs :D
        run: |
          echo "name: ${{ github.event.inputs.name }}"
          echo "home: ${{ github.event.inputs.home }}"
      - run: echo "Getting ready to sleep for 30 seconds"
      - run: echo "Sleeping for 30 seconds..."
      - run: sleep 30
      - run: echo "Done!"
