name: Build and Deploy iOS

# This workflow is run when any tag is published
on:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ./foo.sh
        env:
          SECRET: ${{ secrets.SECRET }}
