name: Tag

# This workflow is run when any tag is published
on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.actor == 'andrew@expensify.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ./foo.sh
        env:
          SECRET: ${{ secrets.SECRET }}
