name: Test Local Action

on:
  push:
    branches: [Rory-TestLocalAction]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Test local action
        uses: Andrew-Test-Org/Public-Test-Repo/.github/actions/composite/myCompositeAction@main
