name: 'Test environment variable in same step'
on:
  push:
    branches: [Rory-TestEnvVar]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "MY_UUID=$(uuidgen)" >> "$GITHUB_ENV"
          echo ${{ env.MY_UUID }}
