name: "Contributor Checklist"

on:
  issue_comment:
    types: [created, edited]

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: contributorChecklist.js
        uses: Andrew-Test-Org/Public-Test-Repo/.github/actions/javascript/contributorChecklist@main
        with:
          COMMENT: ${{ github.event.comment.body }}
