name: Turnstyle test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sleep
        run: sleep 30
      
      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run foo script
        run: ./foo.sh

