name: "Contributor Checklist"

on:
  issue_comment:
    types: [created, edited]

jobs:
  checklist:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: checklist
        with:
          text: ${{ github.event.comment.body }}
          regex: '\s*\#\#\#\#\ Contributor\ \(PR\ Author\)\ Checklist\s*'

      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.checklist.outputs.match == '' }}
        with:
          github_token: ${{ secrets.github_token }}
          body: Checklist is not complete, please make sure to check all the items!

      - name: Checklist Check
        if: ${{ steps.checklist.outputs.match == '' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Checklist not completely filled out')
