name: Test Exit Step
on:
  push:

jobs:
  runTest:
    runs-on: ubuntu-latest
    steps:
      - name: Output 1
        run: |
          echo "Test 1"
      - name: Output 2
        run: |
          echo "Test 2"
      - name: Output Exit
        run: |
          echo "Exiting 1"
          exit 1
      - name: Output 3
        run: |
          echo "Test 3"
      - name: Output 4
        if: ${{ failure() }}
        run: |
          echo "Test 4"
      - name: Output 5
        run: |
          echo "Test 5"
      - name: Output 6
        run: |
          echo "Test 6"
      - name: Output 7
        if: ${{ !failure() }}
        run: |
          echo "Test 7"
      - name: Output 8
        if: ${{ failure() }}
        run: |
          echo "Test 8"
