# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Run node script string
        run: node test.js
        env:
          TEST: true

      - name: Run node script bool
        run: node test.js
        env:
          TEST: ${{ true }}

      # Test secret filter
      - shell: bash
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          echo "The secret is: $SECRET"
