name: 'Workflow that executes on the Issues:Unlabeled event'

on:
  issues:
     types: unlabeled

# new comment

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print labeled event.
        run: echo ${{ toJson(github.event) }}
